In [ ]:
 
 
 
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [ ]:
 %pip install idx2numpy  #To convert standard IDX format MNIST by "yan Lacun" into numpy array

  Created wheel for idx2numpy: filename=idx2numpy-1.2.3-cp37-none-any.whl size=7920 sha256=de887a0a1816336cf6b13061fb91633e0f72a2cbdbe3081d97c2b16f8b48a75e
  Stored in directory: /root/.cache/pip/wheels/7a/c1/da/284ce80a748fab898b8d1fa95468a386e7cf3b81da18511f9d
Successfully built idx2numpy


In [ ]:
 
import pandas
from keras.models import Sequential #swquential is for plain stack of layers with each having one i/p and one o/p
from keras.layers import Dense
#from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [ ]:
 import idx2numpy
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA
 
X_train = idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-train-images-idx3-ubyte')### 60k training images each with 784 pixel elements 
Y_train = idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-train-labels-idx1-ubyte')#### labels--digits for each training image among 60k
X_test=idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-test-images-idx3-ubyte')
Y_test=idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-test-labels-idx1-ubyte')
 
 
print('\ntrain images:',X_train.shape)
print('train labels:',Y_train.shape)
print('test images:',X_test.shape)
print('test labels:',Y_test.shape)


train images: (112800, 28, 28)
train labels: (112800,)
test images: (18800, 28, 28)
test labels: (18800,)


In [ ]:
X_train=X_train.reshape((X_train.shape[0],28,28,1)).astype('float32')
X_test=X_test.reshape((X_test.shape[0],28,28,1)).astype('float32')

In [ ]:
 y_1hot=np_utils.to_categorical(Y_train)
print(y_1hot)
y_1hotTest=np_utils.to_categorical(Y_test)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
 def Conv_OCR_Model():
     model=Sequential()
     model.add(Conv2D(16,kernel_size=(3,3),input_shape=(28,28,1),activation='relu'))
     model.add(MaxPooling2D(pool_size=(2,2),strides=None,padding='valid'))
    # model.add(Dropout(0.5))
     model.add(Flatten())
 
     model.add(Dense(1500,activation='relu',name='i/p-layer'))
     model.add(Dense(1500,activation='relu',name='hidden-layer'))
     model.add(Dense(47,activation='softmax',name='o/p-layer'))
 
     model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])
     return model

In [ ]:
model=Conv_OCR_Model()
hit=model.fit(X_train,y_1hot,epochs=150,batch_size=256,validation_split=0.33,verbose=1)

Epoch 1/150
296/296 [==============================] - 77s 210ms/step - loss: 4.7654 - accuracy: 0.0256 - val_loss: 3.8492 - val_accuracy: 0.0427
Epoch 2/150
296/296 [==============================] - 62s 209ms/step - loss: 3.8489 - accuracy: 0.0437 - val_loss: 3.8476 - val_accuracy: 0.0502
Epoch 3/150
296/296 [==============================] - 62s 209ms/step - loss: 3.8467 - accuracy: 0.0506 - val_loss: 3.8450 - val_accuracy: 0.0677
Epoch 4/150
296/296 [==============================] - 62s 209ms/step - loss: 3.8426 - accuracy: 0.0527 - val_loss: 3.8344 - val_accuracy: 0.0358
Epoch 5/150
296/296 [==============================] - 62s 209ms/step - loss: 3.8214 - accuracy: 0.0447 - val_loss: 3.3162 - val_accuracy: 0.1945
Epoch 6/150
296/296 [==============================] - 62s 209ms/step - loss: 2.2631 - accuracy: 0.3984 - val_loss: 1.7533 - val_accuracy: 0.5609
Epoch 7/150
296/296 [==============================] - 62s 209ms/step - loss: 1.1375 - accuracy: 0.6701 - val_loss: 1.1994 -

In [ ]:
k=hit.history
print(k['accuracy'][0],k['val_accuracy'][0])


NameError: ignored

In [ ]:
l=[1,2,3,4,5,6]
Tacrcy=[0.0256,]
Vacrcy=[]
plt.figure(1)
plt.plot(l,Tacrcy,color='g',marker='o',linestyle='dashed')
plt.plot(l,Vacrcy,color='r',marker='o',linestyle='dashed')
plt.xlabel('No.of Conv Layers')
plt.ylabel('accuracy')
plt.title('Kernels:4,8,16,32,64,128')
plt.legend(['Training','Validation'])
plt.grid()

In [ ]:
import matplotlib.pyplot as plt
plt.plot(hit.history['loss'])
plt.plot(hit.history['val_loss'])
plt.title('loss vs epoch')
plt.xlabel('epochs')
plt.ylabel('loss')
plt.legend(['training_loss','validation_loss'],loc='upper_right')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
plt.plot(hit.history['accuracy'])
plt.plot(hit.history['val_accuracy'])
plt.title('accuracy vs epoch')
plt.xlabel('epochs')
plt.ylabel('accuracy')
plt.legend(['training_accuracy','validation_accuracy'],loc='upper_right')
plt.show()

In [ ]:
 import os
 
import tensorflow as tf
from tensorflow import keras
 
print(tf.version.VERSION)

In [ ]:
 !pip install pyyaml h5py

In [ ]:
 os.listdir(checkpoint_dir)

In [ ]:
 model.evaluate(X_test,y_1hotTest,verbose=1)

In [ ]:
 pred=model.predict_classes(X_test[4].reshape(1,28,28,1))

In [ ]:
 model.summary()

In [ ]:
 #######Confusion matrix
labels_dict ={0:0,1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:'A',11:'B',12:'C',
              13:'D',14:'E',15:'F',16:'G',17:'H',18:'I',19:'J',20:'K',21:'l',
              22:'M',23:'N',24:'O',25:'P',26:'Q',27:'R',28:'S',
              29:'T',30:'u',31:'V',32:'W',33:'X',34:'Y',35:'Z',36:'a',37:'b',
              38:'d',39:'e',40:'f',41:'g',42:'h',43:'n',44:'q',45:'r',46:'t'}

In [ ]:
 List=labels_dict.values()
class_names=list(List)
print(class_names)

In [ ]:
 import io
import itertools
import numpy as np
import sklearn.metrics
import tensorflow as tf
import matplotlib.pyplot as plt
 
from tensorflow import keras
from datetime import datetime
 
%load_ext tensorboard

In [ ]:
 from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
 y_predicts=model.predict(X_test)

In [ ]:
 cm=confusion_matrix(y_1hotTest.argmax(axis=1),y_predicts.argmax(axis=1))
print(cm.shape)

In [ ]:
 print(cm)
plt.imshow(cm)

In [ ]:
    figure = plt.figure(figsize=(20, 15))
    plt.imshow(cm,cmap=plt.cm.Blues)#     interpolation='nearest', cmap=plt.cm.Blues)
    plt.title("Confusion matrix")
    plt.colorbar()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)
     # Normalize the confusion matrix.
    cm = np.around(cm.astype('float') / cm.sum(axis=1)[:, np.newaxis], decimals=2)
    
    # Use white text if squares are dark; otherwise black.
    threshold = cm.max() / 2.
    
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        color = "white" if cm[i, j] > threshold else "black"
        plt.text(j, i, cm[i, j], horizontalalignment="center", color=color)
        
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [ ]:
 print( np.around(cm.astype('float') / cm.sum(axis=1)[:, np.newaxis], decimals=2))