In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [ ]:
1)observe the saturation of layers for 10 epochs and 64 batch size:only conv layers and next dense layers as well
2)remove max pool and observe & chnage the max pool to avg pool
3)add early stop or drop out and observe
2)vary filters (increase and decrease and same) in single layer
3)vary filters in increasing and decreasing and same for sturatable layers
4)vary filter sizes
5)batch size for one layer
6)epochs for 1 layer
7)


In [ ]:
 %pip install idx2numpy  #To convert standard IDX format MNIST by "yan Lacun" into numpy array

  Created wheel for idx2numpy: filename=idx2numpy-1.2.3-cp37-none-any.whl size=7920 sha256=46acd2d49bbc7805f20bb3cb2fcf9a39a47631d9bd887d846564de38690577e2
  Stored in directory: /root/.cache/pip/wheels/7a/c1/da/284ce80a748fab898b8d1fa95468a386e7cf3b81da18511f9d
Successfully built idx2numpy


In [ ]:
 
import pandas
from keras.models import Sequential #swquential is for plain stack of layers with each having one i/p and one o/p
from keras.layers import Dense
#from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [ ]:
 import idx2numpy
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA
 
X_train = idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-train-images-idx3-ubyte')### 60k training images each with 784 pixel elements 
Y_train = idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-train-labels-idx1-ubyte')#### labels--digits for each training image among 60k
X_test=idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-test-images-idx3-ubyte')
Y_test=idx2numpy.convert_from_file('/content/drive/MyDrive/balancedMNIST/emnist-balanced-test-labels-idx1-ubyte')
 
 
print('\ntrain images:',X_train.shape)
print('train labels:',Y_train.shape)
print('test images:',X_test.shape)
print('test labels:',Y_test.shape)


train images: (112800, 28, 28)
train labels: (112800,)
test images: (18800, 28, 28)
test labels: (18800,)


In [ ]:
X_train=X_train.reshape((X_train.shape[0],28,28,1)).astype('float32')
X_test=X_test.reshape((X_test.shape[0],28,28,1)).astype('float32')

In [ ]:
 y_1hot=np_utils.to_categorical(Y_train)
print(y_1hot)
y_1hotTest=np_utils.to_categorical(Y_test)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
layers=[1,2,3,4,5]
Tacrcy=[];
Vacrcy=[];
e=50

model=Sequential()
model.add(Conv2D(8,kernel_size=(3,3),input_shape=(28,28,1),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=None,padding='valid'))
    # model.add(Dropout(0.5))
model.add(Flatten())
 
model.add(Dense(100,activation='relu',name='i/p-layer'))
model.add(Dense(47,activation='softmax',name='o/p-layer'))
 
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])
hit=model.fit(X_train,y_1hot,epochs=e,validation_split=0.33,batch_size=64,verbose=1)
k=hit.history
Tacrcy.append(k['accuracy'][e-1])
Vacrcy.append(k['val_accuracy'][e-1])

Epoch 1/50
1181/1181 [==============================] - 22s 19ms/step - loss: 4.0798 - accuracy: 0.1107 - val_loss: 2.0951 - val_accuracy: 0.4249
Epoch 2/50
1181/1181 [==============================] - 21s 18ms/step - loss: 1.8848 - accuracy: 0.4788 - val_loss: 1.5729 - val_accuracy: 0.5712
Epoch 3/50
1181/1181 [==============================] - 21s 18ms/step - loss: 1.4446 - accuracy: 0.5883 - val_loss: 1.2964 - val_accuracy: 0.6232
Epoch 4/50
1008/1181 [========================>.....] - ETA: 2s - loss: 1.2154 - accuracy: 0.6413